name: Deploy

on:
    workflow_dispatch:

jobs:
    deploy:
        name: Run deploy script
        runs-on: self-hosted

        steps:
            - run: |
                cd /scripts
                ./afterpull.sh